# Use an official Python runtime as a parent image
FROM python:3.12.1

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt file to WORKDIR
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the WORKDIR
COPY . .

# Expose port 8000 for the Django development server
EXPOSE 8000

# Start the development server when the container starts
CMD python manage.py runserver 0.0.0.0:8000
